Repository CodeTheChangeUBC/OLPC, pull requests merged in 2018-05, with the labels that each got.

#53 Added some leaderboard and high score functionality
  Metris2.0/Leaderboard.txt
  Metris2.0/inputbox.py
  Metris2.0/inputbox.pyc
  Metris2.0/leaderboard.json
  Metris2.0/leaderboard.py
  Metris2.0/leaderboard.pyc
  Metris2.0/metris.py
Labels: Feature, bug

#112 created newBlock function and moved it out of the while loop
  Metris/Metris.py
Labels: enhancement

#121 capped menu fps at 60
  Metris/pygameMenu/menu.py
Labels: enhancement

#123 capped menu fps at ~60
  Metris/pygameMenu/menu.py
Labels: bug

#147 Inputbox
  Metris/Metris.py
  Metris/inputbox.py
  Metris/leaderboard.json
  Metris/menu.py
  Metris/pygameMenu/textmenu.py
Labels: enhancement

#170 changed msgs, changed qs
  Metris.py
Labels: Feature, enhancement

#171 controls enabled if bonus question wrong
  Metris.py
Labels: enhancement

#172 updates leaderboard after restarting
  Metris.py
  pygameMenu/menu.py
Labels: Feature, enhancement
